//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationBot.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslationBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   chat_history.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HistoryFileName {
            get {
                return ResourceManager.GetString("HistoryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ar,bg,zh-Hans,cs,da,nl,en,fr,de,hi,it,ja,ko,nb,pl,pt,ro,ru,es,sv,tr に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NMTSupportLanguageCode {
            get {
                return ResourceManager.GetString("NMTSupportLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputCommandName {
            get {
                return ResourceManager.GetString("OutputCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RestreamChat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestreamChatFolderName {
            get {
                return ResourceManager.GetString("RestreamChatFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   af,ar,bn,bs,bg,yue,ca,zh-Hans,zh-Hant,hr,cs,da,nl,en,et,fj,fil,fi,fr,de,el,ht,he,hi,mww,hu,id,it,ja,sw,tlh,tlh-Qaak,ko,lv,lt,mg,ms,mt,nb,fa,pl,pt,otq,ro,ru,sm,sr-Cyrl,sr-Latn,sk,sl,es,sv,ty,ta,th,to,tr,uk,ur,vi,cy,yua に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMTSupportLanguageCode {
            get {
                return ResourceManager.GetString("SMTSupportLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartButtonStartText {
            get {
                return ResourceManager.GetString("StartButtonStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartButtonStopText {
            get {
                return ResourceManager.GetString("StartButtonStopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   https://api.cognitive.microsofttranslator.com/{0}?api-version=3.0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TranslatorTextAPIEndpoint {
            get {
                return ResourceManager.GetString("TranslatorTextAPIEndpoint", resourceCulture);
            }
        }
    }
}
